export const countriesConstants ={
    RECEIVE_COUNTRIES_DETAILS_REQUEST: 'RECEIVE_COUNTRIES_DETAILS_REQUEST',
    RECEIVE_COUNTRIES_DETAILS_SUCCESS: 'RECEIVE_COUNTRIES_DETAILS_SUCCESS',
    RECEIVE_COUNTRIES_DETAILS_FAILURE: 'RECEIVE_COUNTRIES_DETAILS_FAILURE'
};
  